config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index', as: 'home'

  resources :companies
  resources :users
  resources :sales
  resources :data, only: [:index]
  resource :session, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_one :company

    validates :first_name, :last_name, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates(
        :email,
        presence: true,
        uniqueness: true,
        format: VALID_EMAIL_REGEX
    )

    def full_name
        first_name + " " + last_name
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new user_params

        if @user.save
            session[:user_id] = @user.id 
            redirect_to home_path
        else
            render :new
        end
    end

    def show
        @user = User.find params[:id]
        @company = current_user.company
    end

    private
    def user_params
        params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/views/users/new.html.erb
<div class="container border rounded p-5" id="sign-in">
  <h2 class="text-center">SIGN UP</h2>

  <%= simple_form_for @user do |f| %>
  <% if @user.errors.present? %>
        <p>
            <%= @user.errors.full_messages.join(', ') %>
        </p>
    <% end %>

    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>

    <%= f.submit "Sign Up", class: "btn btn-primary btn-lg btn-block" %>
  <% end %>
  <br>
  <p class="text-center">Already registered? <%= link_to 'Sign in here', new_session_path %></p>
</div>

app/views/users/show.html.erb
<h2><%= fa_stacked_icon "user-circle" %><%= @user.full_name %>'s Profile</h2>

<div class="container border rounded p-5" style="background-color: white;">
    <% if @company %>
        <h5 >Your registered company:</h5>
        <h2><%= link_to @company.name, company_path(@company.id) %></h2>
        <h4><%= @company.industry.name %></h4>

        <% if @company.subindustry %>
            <p><%= @company.subindustry.name %></p>
        <% end %>

        <p>
        <% if @company.subregion %>
            <%= @company.subregion.name%>,
        <% end %>
        <%= @company.region.name %>
        </p>

        <%= link_to 'Edit Company', edit_company_path, class: 'btn btn-outline-primary' %>
        <%= link_to( 
            'Delete Company', 
            company_path(@company), 
            method: :delete,
            data: {
                confirm: 'Are you sure?'
            },
            class: 'btn btn-outline-primary'
        ) %>
</div>
<% else %>
    <p>Hi, <%= @user.first_name %>! In order to get access to personalized data resources, you'll need to register your company. To register your company, click on the button below.</p>
    <%= link_to "Register Your Company", new_company_path, class: "btn btn-success"%>
<% end %>