config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index', as: 'home'

  resources :companies
  resources :users
  resources :sales
  resources :data, only: [:index]
  resource :session, only: [:new, :create, :destroy]
end

app/models/company.rb
class Company < ApplicationRecord
    belongs_to :user
    belongs_to :industry
    belongs_to :subindustry, optional: true
    belongs_to :region
    belongs_to :subregion, optional: true
    has_many :sales, dependent: :destroy

    # Search method for given company's industry sales by region, industry, and year
    def self.data(company)
        data = {}

        # If sub-categories exist, use those, otherwise use the parent categories
        r = company.subregion ? 'subregion' : 'region'
        i = company.subindustry ? 'subindustry' : 'industry'

        r_id = company.subregion ? company.subregion.id : company.region.id
        i_id = company.subindustry ? company.subindustry.id : company.industry.id

        # Search the db and push results to a 'data' hash
        Sale.where(
            "#{r}_id = ? AND #{i}_id = ? AND company_id IS ?",
            r_id, i_id, nil).each {|item| data["#{item.month}, #{item.year}"] = item.value}

        # Some subindustries do not have results for certain years
        # in this case, use the parent industry data for display
        if data.empty?
            Sale.where(
                "#{r}_id = ? AND industry_id = ? AND company_id IS ?",
                r_id, company.industry.id, nil).each {|item| data["#{item.month}, #{item.year}"] = item.value}
        else
            return data
        end

        return data
    end

    # Search method for company-specific sales data
    def self.sales(company)
        sale = {}

        Sale.where("company_id = ?", company.id)
            .each {|item| sale["#{item.month}, #{item.year}"] = item.value}

        return sale
    end

    # Search and sum all industry sales for a given region and year per industry
    def self.industry_sales(company, year)
        r = company.subregion ? 'subregion' : 'region'
        r_id = company.subregion ? company.subregion.id : company.region.id

        data = {}

        sales = Sale.where(
            "#{r}_id = ? AND year = ? AND company_id IS ?", r_id, year, nil)

        industries = (1..11).to_a

        industries.each do |industry|
            data[industry] = sales.where(industry: industry).pluck(:value).sum
        end

        return data
    end

    def sum
        
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

    def new
        @company = Company.new
        @industry = Industry.all
        @subindustry = Subindustry.all 
        @region = Region.all 
    end

    def create
        @company = Company.new company_params
        @company.user = current_user

        if @company.city.downcase == "vancouver"
            @company.subregion_id = 1
        elsif @company.city.downcase == "toronto"
            @company.subregion_id = 2
        elsif @company.city.downcase == "montreal"
            @company.subregion_id = 3
        end

        if @company.save
            redirect_to company_path(@company.id)
        else
            render :new
        end
    end

    def show
        @company = Company.find params[:id]

        @data = Company.data(@company)
        @sales = Company.sales(@company)

        @industry_sales = Company.industry_sales(@company, 2017)
        @sum = @industry_sales.values.inject { |a, b| a + b }
        
        @industry_sales16 = Company.industry_sales(@company, 2016)
        @industry_sales15 = Company.industry_sales(@company, 2015)

        @total17 = @industry_sales.values_at(@company.industry_id)[0]
        @total16 = @industry_sales16.values_at(@company.industry_id)[0]
        @total15 = @industry_sales15.values_at(@company.industry_id)[0]

        if !@sales.empty?
            @total_sales = @sales.values.sum
            @avg_sales = @total_sales/(@sales.values.count)
                if @sales.count == 24
                    @sales16 = @sales.values[0..11].sum
                    @sales17 = @sales.values[12..24].sum
                end
        end
    end

    def index
        @companies = Company.order(created_at: :desc)
    end

    def edit
        @company = current_user.company
        @industry = Industry.all
        @subindustry = Subindustry.all 
        @region = Region.all
    end

    def update
        @company = current_user.company

        if @company.update(company_params)
            redirect_to company_path(@company)
        else
            render :edit
        end
    end

    def destroy
        @company = Company.find params[:id]
        @company.destroy
        redirect_to home_path
    end

    private
    def company_params
        params.require(:company).permit(:name, :region_id, :subregion_id, :industry_id, :subindustry_id, :address, :city)
    end
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
    <% if @company.errors.present? %>
        <p> 
            <%= @company.errors.full_messages.join(', ') %>
        </p>
    <% end %>

    <%= f.input :name, label: 'Company Name' %>
    <%= f.input :address, label: 'Address', placeholder: 'E.g. 123 Electric Avenue' %>

    <div class="row">
        <div class="col-6">
        <%= f.input :city, label: 'City' %>
        </div>
        <div class="col-6">
        <%= f.input :region_id, label: 'Province/Territory', collection: @region, input_html: { class: 'chosen-select', id: 'region-selector' }  %>
        </div>
    </div>

    <h2>Select your Industry:</h2>

    <%= f.input :industry_id, label: 'Industry', collection: @industry, input_html: { class: 'chosen-select', id: 'industry-selector' } %>
    <%= f.input :subindustry_id, label: 'Sub-Industry (if applicable)', collection: @subindustry, wrapper_html: { class: 'chosen-select hidden', id: 'subindustry-selector' } %>

    <%= f.submit class: 'btn btn-primary'%>

<% end %>

app/views/companies/edit.html.erb
<div class="container border rounded p-5" id="company-register">
    <h1>Edit Your Company Details:</h1>

    <%= render 'form' %>
</div>

app/views/companies/index.html.erb
<h1>Company Index</h1>

<ul>
    <% @companies.each do |company| %>
        <li>
            <%= link_to company.name, company_path(company.id) %>
            <br>
            <small>
                Posted <%= time_ago_in_words(company.created_at) %> ago
            </small>
        </li>
    <% end %>
</ul>

app/views/companies/new.html.erb
<div class="container border rounded p-5" id="company-register">
    <h1>Register Your Company:</h1>

    <%= simple_form_for(@company) do |f| %>
        <% if @company.errors.present? %>
            <p> 
                <%= @company.errors.full_messages.join(', ') %>
            </p>
        <% end %>

        <%= f.input :name, label: 'Company Name' %>
        <%= f.input :address, label: 'Address', placeholder: 'E.g. 123 Electric Avenue' %>

        <div class="row">
            <div class="col-6">
            <%= f.input :city, label: 'City' %>
            </div>
            <div class="col-6">
            <%= f.input :region_id, label: 'Province/Territory', collection: @region, input_html: { class: 'chosen-select', id: 'region-selector' }  %>
            </div>
        </div>

        <h2>Select your Industry:</h2>

        <%= f.input :industry_id, label: 'Industry', collection: @industry, input_html: { class: 'chosen-select', id: 'industry-selector' } %>
        <%= f.input :subindustry_id, label: 'Sub-Industry (if applicable)', collection: @subindustry, wrapper_html: { class: 'chosen-select hidden', id: 'subindustry-selector' } %>

        <%= f.submit class: 'btn btn-primary'%>

    <% end %>
</div>

app/views/companies/show.html.erb
<div class="container border rounded p-3" style="background-color: white;">
    <h1 class="bold"><%= @company.name %></h1>
    <h2><%= @company.industry.name %></h2>
    <% if @company.subindustry %>
        <h3><%= @company.subindustry.name %></h3>
    <% end %>
    <h4>
        <% if @company.subregion %>
            <%= @company.subregion.name%>,
        <% end %>
        <%= @company.region.name %>
    </h4>
    <%= link_to 'Add Your Company Data', new_sale_path, class: 'btn btn-success'%>
    <%= link_to 'View Sales Data', sales_path, class: 'btn btn-primary'%>
</div>
<hr>
<% if @sales.empty? %>
    <h2><b>INDUSTRY OVERVIEW:</b>
        <%= @company.industry.name %> in 
        <% if @company.subregion %>
            <%= @company.subregion.name%>,
        <% end %>
        <%= @company.region.name %>
    </h2>
    <div class="card border-danger mb-3">
        <div class="card-body text-danger">
            <p class="card-text">To get personalized sales statistics, add your 2016-2017 sales data!</p>
        </div>
    </div>
<% else %>
    <h3><b>PERSONALIZED INSIGHTS:</b>
        <%= @company.industry.name %> in 
        <% if @company.subregion %>
            <%= @company.subregion.name%>,
        <% end %>
        <%= @company.region.name %></h3>
<% end %>

<% if !@sales.empty? %>
    <div class="row">
        <div class="col-6">
            <form>
                <div class="form-group">
                    <label for="year-selector">Select Year:</label>
                    <select class="form-control" id='year-selector-dual'>
                        <option selected="selected" value="2017">2017</option>
                        <option value="2016">2016</option>
                    </select>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
            <canvas id="dual-chart" data-sales='<%= raw @sales.to_json %>'></canvas>
        </div>
        <div class="col-4">
            <div class="card border-primary mb-3">
                <div class="card-header">How do your sales compare?</div>
                <div class="card-body text-dark">
                    <p class="card-text">Your sales growth over 2016-2017 was <b><%= number_to_percentage((@sales17.to_f/@sales16.to_f - 1) * 100) %></b>. Other businesses in your region saw <b><%= number_to_percentage((@total17.to_f/@total16.to_f - 1) * 100) %></b> growth over the same period.</p>
                </div>
            </div>
            <table class="table table-striped">
            <tbody>
                <tr>
                    <td class="font-weight-bold">Sales in 2017</td>
                    <td><%= number_to_currency(@sales17, precision: 0) %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">Sales in 2016</td>
                    <td><%= number_to_currency(@sales16, precision: 0) %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">Growth in Sales (2016-17)</td>
                    <td><%= number_to_percentage((@sales17.to_f/@sales16.to_f - 1) * 100) %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">Average Monthly Sales</td>
                    <td>$<%= @avg_sales%></td>
                </tr>
            </tbody>
            </table>
        </div>
    </div>
    <hr>
<% end %>

<div class="row">
    <div class="col-6">
        <form>
            <div class="form-group">
                <label for="year-selector">Select Year:</label>
                <select class="form-control" id='year-selector'>
                    <option selected="selected" value="2017">2017</option>
                    <option value="2016">2016</option>
                    <option value="2015">2015</option>
                    <option value="2014">2014</option>
                    <option value="2013">2013</option>
                    <option value="2012">2012</option>
                    <option value="2011">2011</option>
                    <option value="2010">2010</option>
                </select>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-7">
        <h5><%= @company.industry.name %> Sales:</h5>
        <canvas id="single-chart" data-sales='<%= raw @data.to_json %>'></canvas>
    </div>
    <div class="col-5">
        <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Year</th>
                <th scope="col">Total Sales</th>
                <th scope="col">Growth</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>2017</td>
                <td><%= number_to_currency(@total17, precision: 0) %></td>
                <td><%= number_to_percentage((@total17.to_f/@total16.to_f - 1) * 100) %></td>
            </tr>
            <tr>
                <td>2016</td>
                <td><%= number_to_currency(@total16, precision: 0) %></td>
                <td><%= number_to_percentage((@total16.to_f/@total15.to_f - 1) * 100) %></td>
            </tr>
        </tbody>
        </table>
        <div class="card text-dark bg-outline-primary mb-3">
            <div class="card-header">Summary Data:</div>
            <div class="card-body">
                <h4 class="card-title"><%= @company.industry.name %></h4>
                <p class="card-text">Overall sales for <%= @company.industry.name %>s in <%= @company.region.name %> grew <b><%= number_to_percentage((@total17.to_f/@total16.to_f - 1) * 100) %></b> over 2016-2017!</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-8">
        <h5>How other industries in your region compare:</h5>
        <canvas id="doughnut-chart" data-sales='<%= raw @industry_sales.to_json %>'></canvas>
    </div>
    <div class="col-4">
        <div class="card text-dark bg-border-primary mb-3 mt-5">
            <div class="card-header">Industry Share:</div>
            <div class="card-body">
                <p class="card-text">Overall sales for <%= @company.industry.name %>s in <%= @company.region.name%> account for <b><%= number_to_percentage((@total17.to_f/@sum.to_f) * 100) %></b> of total retail sales in Vancouver in 2017.</p>
            </div>
        </div>
    </div>
</div>