config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index', as: 'home'

  resources :companies
  resources :users
  resources :sales
  resources :data, only: [:index]
  resource :session, only: [:new, :create, :destroy]
end

app/models/sale.rb
class Sale < ApplicationRecord
    belongs_to :company, optional: true
    belongs_to :industry, optional: true
    belongs_to :subindustry, optional: true
    belongs_to :region, optional: true
    belongs_to :subregion, optional: true

    validates :value, presence: true
    validates :company, uniqueness: { scope: [:month, :year] }
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

    def index
        @company = current_user.company
        @sales = Sale.where(company_id: current_user.company)

        @months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    end

    def new
        @sale = Sale.new
        @company = current_user.company
        @sales = Sale.where(company_id: current_user.company)

        @years = [2017, 2016]
        @months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    end

    def create
        params[:sales].each do |sale_params|
            if sale_params['value'].present?
                @sale = Sale.new(
                    value: sale_params[:value],
                    month: sale_params[:month],
                    year: sale_params[:year],
                    company: current_user.company,
                    industry_id: current_user.company.industry_id,
                    subindustry_id: current_user.company.subindustry_id,
                    region_id: current_user.company.region_id,
                    subregion_id: current_user.company.subregion_id
                )

                if !@sale.save
                    flash[:danger] = "Sales data already exists"
                    redirect_to new_sale_path and return
                end
            end
        end

        flash[:success] = "Sales saved"
        redirect_to sales_path
    end

    def edit
        @sale = Sale.find params[:id]

        respond_to do |format|
            format.html
            format.js
        end
    end

    def update
        @sale = Sale.find params[:id]

        if @sale.update(params.require(:sale).permit(:value))
            redirect_to sales_path
        else
            flash[:danger] = "Error"
            redirect_to sales_path
        end
    end

    def destroy
        @sale = Sale.find params[:id]
        @sale.destroy

        redirect_to sales_path
    end
end

app/views/sales/_edit.html.erb
<%= simple_form_for @sale do |f| %>
  <h4><%= @sale.year %></h4>
  <div class="row">
    <div class="col-2 mt-1">
      <%= @sale.month %>
    </div>
    <div class="col-8 mr-5">
      <%= f.input :value, label: false %>
    </div>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
<% if @sale.errors.present? %>
    <p>
        <%= @sale.errors.full_messages.join(', ') %>
    </p>
<% end %>

<% @years.each { |year| %>
<div class="card" style="width: 25rem;">
    <div class="card-body">
        <h4 class="card-title">
            <%= year %>
            <span class="fa fa-angle-down ml-auto"></span>
        </h4>
        <div class = "card-text hidden">
            <div class="row">
                <div class="col-4">
                    <h5>Month</h5>
                </div>
                <div class="col-8">
                    <h5>Sales ($)</h5>
                </div>
            </div>
            <% @months.each { |month| %>
            <div class="row">
                <div class="col-4 mt-1">
                    <p><%= month %>
                </div>
                <div class="col-8">
                    <%= f.input :year, as: :hidden, input_html: { value: year, name: 'sales[][year]' } %>
                    <%= f.input :month, as: :hidden, input_html: { value: month, name: 'sales[][month]' } %>
                    <%= f.input :value, label: false, input_html: { name: 'sales[][value]' } %>
                </div>
            </div>
            <% } %>
        </div>
    </div>
</div>
<br>
<% } %>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/sales/edit.js.erb
$("#editSaleModal").find(".modal-body").html("<%= j (render './sales/edit.html.erb') %>");
$("#editSaleModal").modal()

app/views/sales/index.html.erb
<h2><%= @company.name %> Sales Data:</h2>

<% if @sales.empty? %>
<p>You have no sales to show!</p>
    <%= link_to 'Add Your Sales', new_sale_path, class: 'btn btn-success'%>
<% else %>
    <%= link_to 'Add Sales', new_sale_path, class: 'btn btn-success'%>
    <%= link_to 'Company Dashboard', company_path(@company.id), class: 'btn btn-primary'%>

    <p class="mt-3">Edit or delete your sales data here:</p>
    <div class="row">
        <div class="col-5">
            <h2>2017</h2>
        </div>
        <div class="col-6">
            <h2>2016</h2>
        </div>
    </div>
    <div class="row">
        <table class="table col-5 border mr-2" style="background-color: white;">
            <tr>
                <th>Month</th>
                <th>Revenue ($)</th>
                <th>Edit or Delete</th>
            </tr>
            <% @months.each do |month| %>
                <tr>
                    <td><%= month %></td>
                    <% sale = @sales.where(month: month, year: 2017).first %>
                    <% if sale.present? %>
                        <td>
                            <%= number_to_currency(sale.value, precision: 0) %>
                        </td>
                        <td class="p-2">
                            <%= link_to("Edit", edit_sale_path(sale), {class: "btn btn-outline-primary", remote: true, 'data-toggle' =>  "modal", 'data-target' => '#editSaleModal'}) %>
                            <%= link_to("Delete", sale_path(sale), method: :delete, class: "btn btn-outline-primary") %>
                        </td>
                    <% else %>
                        <td> [No Data] </td>
                        <td class="p-2"> <%= link_to 'Add Sale', new_sale_path, class: 'btn btn-outline-success' %> </td>
                    <% end %>
                </tr>
            <% end %>
        </table>
        
        <table class="table col-5 border" style="background-color: white;">
            <tr>
                <th>Month</th>
                <th>Revenue ($)</th>
                <th>Edit or Delete</th>
            </tr>
            <% @months.each do |month| %>
                <tr>
                    <td><%= month %></td>
                    <% sale = @sales.where(month: month, year: 2016).first %>
                    <% if sale.present? %>
                        <td>
                            <%= number_to_currency(sale.value, precision: 0) %>
                        </td>
                        <td class="p-2">
                            <%= link_to("Edit", edit_sale_path(sale), {class: "btn btn-outline-primary", remote: true, 'data-toggle' =>  "modal", 'data-target' => '#editSaleModal'}) %>
                            <%= link_to("Delete", sale_path(sale), method: :delete, class: "btn btn-outline-primary") %>
                        </td>
                    <% else %>
                        <td> [No Data] </td>
                        <td class="p-2"> <%= link_to 'Add Sale', new_sale_path, class: 'btn btn-outline-success' %> </td>
                    <% end %>
                </tr>
            <% end %>
        </table>
    </div>
<% end %>

<!-- Modal -->
    <div class="modal fade" id="editSaleModal" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="saleEdit">Update Sale</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

app/views/sales/new.html.erb
<h1><%= @company.name %>'s Sales</h1>
<p>Add new sales with this form. Disabled fields are already saved - to edit them, go to your <%= link_to 'sales data', sales_path %> page</p>
<%= simple_form_for(@sale) do |f| %>

<div class="row" style="width: 900px;">
    <% @years.each { |year| %>
    <div class="card col-5 mr-2">
        <div class="card-body">
            <h4 class="card-title">
                <%= year %>
            </h4>
            <div class = "card-text">
                <div class="row">
                    <div class="col-5">
                        <h5>Month</h5>
                    </div>
                    <div class="col-7">
                        <h5>Sales ($)</h5>
                    </div>
                </div>
                <% @months.each { |month| %>
                <div class="row" style="height: 40px;">
                    <div class="col-5 mt-1">
                        <p><%= month %></p>
                    </div>
                    <div class="col-7">
                        <%= f.input :year, as: :hidden, input_html: { value: year, name: 'sales[][year]' } %>
                        <%= f.input :month, as: :hidden, input_html: { value: month, name: 'sales[][month]' } %>
                        <% sale = @sales.where(month: month, year: year).first %>
                        <% if sale.present? %>
                            <%= f.input :value, label: false, disabled: true, placeholder: 'Saved' %>
                        <% else %>
                            <%= f.input :value, label: false, input_html: { name: 'sales[][value]' } %>
                        <% end %>
                    </div>
                </div>
                <% } %>
            </div>
        </div>
    </div>
    <% } %>
</div>
<br>
<%= f.submit "Save Sales", class: 'btn btn-primary', wrapper_html: { id: 'sale-submit' } %>
<% end %>