config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index', as: 'home'

  resources :companies
  resources :users
  resources :sales
  resources :data, only: [:index]
  resource :session, only: [:new, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RetailGenie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary px-5">
        <%= link_to image_tag("retail_genie_logo.png", alt: "logo"), '/', class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <% if current_user.present? %>
              <li class="nav-item">
                <%= link_to 'My Account', user_path(current_user), class: 'nav-link' %>
              </li>
            <% if current_user.company %>
              <li class="nav-item">
                <%= link_to 'Company Dashboard', company_path(current_user.company), class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to '<i class="fa fa-sign-out"></i> Sign Out'.html_safe, session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to '<i class="fa fa-user"></i> Login'.html_safe, new_session_path, class: 'nav-link' %> 
              </li>
              <li class="nav-item">
                <%= link_to '<i class="fa fa-sign-in"></i> Sign Up'.html_safe, new_user_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      </header>

    <div class="container mt-4">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %> alert-dismissible fade show">
          <%= message %>
        </div>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>